// Code generated by Slice Machine. DO NOT EDIT.

import AboutUs from './AboutUs/index.svelte';
import Clients from './Clients/index.svelte';
import Intro from './Intro/index.svelte';
import RichText from './RichText/index.svelte';
import SecondScreenProject from './SecondScreenProject/index.svelte';
import Services from './Services/index.svelte';
import WorkHeader from './WorkHeader/index.svelte';
import WorksScreen from './WorksScreen/index.svelte';

export const components = {
  abount_us: AboutUs,
  clients: Clients,
  intro: Intro,
  rich_text: RichText,
  second_screen_project: SecondScreenProject,
  services: Services,
  work_header: WorkHeader,
  works_screen: WorksScreen,
};
