// Code generated by Slice Machine. DO NOT EDIT.

import AboutUs from './AboutUs/index.svelte';
import Awards from './Awards/index.svelte';
import Clients from './Clients/index.svelte';
import Intro from './Intro/index.svelte';
import NextProjects from './NextProjects/index.svelte';
import ProjectBlock from './ProjectBlock/index.svelte';
import SecondScreenProject from './SecondScreenProject/index.svelte';
import Services from './Services/index.svelte';
import TripleC from './TripleC/index.svelte';
import ProjectHeader from './ProjectHeader/index.svelte';
import WorksScreen from './WorksScreen/index.svelte';

export const components = {
  abount_us: AboutUs,
  awards: Awards,
  clients: Clients,
  intro: Intro,
  next_projects: NextProjects,
  project_block: ProjectBlock,
  second_screen_project: SecondScreenProject,
  services: Services,
  triple_c: TripleC,
  work_header: ProjectHeader,
  works_screen: WorksScreen,
};
