// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | AwardsSlice
  | TripleCSlice
  | AbountUsSlice
  | ServicesSlice
  | ClientsSlice
  | WorksScreenSlice
  | SecondScreenProjectSlice
  | IntroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site TItle field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, 'settings', Lang>;

type Work1DocumentDataSlicesSlice = ProjectBlockSlice | WorkHeaderSlice;

/**
 * Content for Work (Project) documents
 */
interface Work1DocumentData {
  /**
   * Slice Zone field in *Work (Project)*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work_1.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<Work1DocumentDataSlicesSlice>;
}

/**
 * Work (Project) document from Prismic
 *
 * - **API ID**: `work_1`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Work1Document<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<Work1DocumentData>, 'work_1', Lang>;

export type AllDocumentTypes = PageDocument | SettingsDocument | Work1Document;

/**
 * Item in *AboutUs → Default → Primary → Numbers*
 */
export interface AbountUsSliceDefaultPrimaryNumbersItem {
  /**
   * Count field in *AboutUs → Default → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.numbers[].count
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  count: prismic.KeyTextField;

  /**
   * Label field in *AboutUs → Default → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.numbers[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AbountUsSliceDefaultPrimary {
  /**
   * Description field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Numbers field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.numbers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  numbers: prismic.GroupField<Simplify<AbountUsSliceDefaultPrimaryNumbersItem>>;

  /**
   * Philosophy field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.philosophy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  philosophy: prismic.RichTextField;

  /**
   * Image field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Belief field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abount_us.default.primary.belief
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  belief: prismic.RichTextField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AbountUsSliceDefault = prismic.SharedSliceVariation<'default', Simplify<AbountUsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *AboutUs*
 */
type AbountUsSliceVariation = AbountUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `abount_us`
 * - **Description**: AbountUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AbountUsSlice = prismic.SharedSlice<'abount_us', AbountUsSliceVariation>;

/**
 * Item in *Awards → Default → Primary → Awards*
 */
export interface AwardsSliceDefaultPrimaryAwardsItem {
  /**
   * Image field in *Awards → Default → Primary → Awards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.awards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Awards → Default → Primary → Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.awards[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Award field in *Awards → Default → Primary → Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.awards[].award
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  award: prismic.KeyTextField;

  /**
   * Year field in *Awards → Default → Primary → Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.awards[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Primary content in *Awards → Default → Primary*
 */
export interface AwardsSliceDefaultPrimary {
  /**
   * Awards field in *Awards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.awards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  awards: prismic.GroupField<Simplify<AwardsSliceDefaultPrimaryAwardsItem>>;
}

/**
 * Default variation for Awards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSliceDefault = prismic.SharedSliceVariation<'default', Simplify<AwardsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Awards*
 */
type AwardsSliceVariation = AwardsSliceDefault;

/**
 * Awards Shared Slice
 *
 * - **API ID**: `awards`
 * - **Description**: Awards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSlice = prismic.SharedSlice<'awards', AwardsSliceVariation>;

/**
 * Item in *Clients → Default → Primary → Clients*
 */
export interface ClientsSliceDefaultPrimaryClientsItem {
  /**
   * Name field in *Clients → Default → Primary → Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clients[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Clients → Default → Primary → Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clients[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Clients → Default → Primary*
 */
export interface ClientsSliceDefaultPrimary {
  /**
   * Clients field in *Clients → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clients[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  clients: prismic.GroupField<Simplify<ClientsSliceDefaultPrimaryClientsItem>>;
}

/**
 * Default variation for Clients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<'default', Simplify<ClientsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Clients*
 */
type ClientsSliceVariation = ClientsSliceDefault;

/**
 * Clients Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSlice = prismic.SharedSlice<'clients', ClientsSliceVariation>;

/**
 * Item in *Intro → Default → Primary → Intro Works*
 */
export interface IntroSliceDefaultPrimaryIntroWorksItem {
  /**
   * Thumbnail field in *Intro → Default → Primary → Intro Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.intro_works[].thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Primary content in *Intro → Default → Primary*
 */
export interface IntroSliceDefaultPrimary {
  /**
   * Description field in *Intro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Intro Works field in *Intro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.intro_works[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  intro_works: prismic.GroupField<Simplify<IntroSliceDefaultPrimaryIntroWorksItem>>;

  /**
   * Number of Works field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 9
   * - **API ID Path**: intro.default.primary.number_of_works
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_of_works: prismic.KeyTextField;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSliceDefault = prismic.SharedSliceVariation<'default', Simplify<IntroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Intro*
 */
type IntroSliceVariation = IntroSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: Intro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSlice = prismic.SharedSlice<'intro', IntroSliceVariation>;

/**
 * Primary content in *ProjectBlock → Big Image → Primary*
 */
export interface ProjectBlockSliceDefaultPrimary {
  /**
   * Image field in *ProjectBlock → Big Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Big Image variation for ProjectBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSliceDefault = prismic.SharedSliceVariation<'default', Simplify<ProjectBlockSliceDefaultPrimary>, never>;

/**
 * Primary content in *ProjectBlock → Two Images in a Row → Primary*
 */
export interface ProjectBlockSliceTwoImagesInARowPrimary {
  /**
   * Image 1 field in *ProjectBlock → Two Images in a Row → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_block.twoImagesInARow.primary.left_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_image: prismic.ImageField<never>;

  /**
   * Image 2 field in *ProjectBlock → Two Images in a Row → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_block.twoImagesInARow.primary.rightimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  rightimage: prismic.ImageField<never>;
}

/**
 * Two Images in a Row variation for ProjectBlock Slice
 *
 * - **API ID**: `twoImagesInARow`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSliceTwoImagesInARow = prismic.SharedSliceVariation<'twoImagesInARow', Simplify<ProjectBlockSliceTwoImagesInARowPrimary>, never>;

/**
 * Primary content in *ProjectBlock → Big Text → Primary*
 */
export interface ProjectBlockSliceBigTextPrimary {
  /**
   * Title field in *ProjectBlock → Big Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title in braces above the text
   * - **API ID Path**: project_block.bigText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ProjectBlock → Big Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text content
   * - **API ID Path**: project_block.bigText.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Big Text variation for ProjectBlock Slice
 *
 * - **API ID**: `bigText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSliceBigText = prismic.SharedSliceVariation<'bigText', Simplify<ProjectBlockSliceBigTextPrimary>, never>;

/**
 * Primary content in *ProjectBlock → Two Columns Text → Primary*
 */
export interface ProjectBlockSliceTwoColumnsTextPrimary {
  /**
   * Title field in *ProjectBlock → Two Columns Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title in braces
   * - **API ID Path**: project_block.twoColumnsText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ProjectBlock → Two Columns Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text content
   * - **API ID Path**: project_block.twoColumnsText.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Two Columns Text variation for ProjectBlock Slice
 *
 * - **API ID**: `twoColumnsText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSliceTwoColumnsText = prismic.SharedSliceVariation<'twoColumnsText', Simplify<ProjectBlockSliceTwoColumnsTextPrimary>, never>;

/**
 * Primary content in *ProjectBlock → Gap → Primary*
 */
export interface ProjectBlockSliceGapPrimary {
  /**
   * Desktop field in *ProjectBlock → Gap → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: A gap in pixels on desktop devices
   * - **API ID Path**: project_block.gap.primary.desktop
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  desktop: prismic.NumberField;

  /**
   * Mobile field in *ProjectBlock → Gap → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: A gap in pixels on mobile devices
   * - **API ID Path**: project_block.gap.primary.mobile
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  mobile: prismic.NumberField;
}

/**
 * Gap variation for ProjectBlock Slice
 *
 * - **API ID**: `gap`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSliceGap = prismic.SharedSliceVariation<'gap', Simplify<ProjectBlockSliceGapPrimary>, never>;

/**
 * Primary content in *ProjectBlock → Divider → Primary*
 */
export interface ProjectBlockSliceDividerPrimary {
  /**
   * Extended field in *ProjectBlock → Divider → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project_block.divider.primary.extended
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  extended: prismic.BooleanField;
}

/**
 * Divider variation for ProjectBlock Slice
 *
 * - **API ID**: `divider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSliceDivider = prismic.SharedSliceVariation<'divider', Simplify<ProjectBlockSliceDividerPrimary>, never>;

/**
 * Slice variation for *ProjectBlock*
 */
type ProjectBlockSliceVariation =
  | ProjectBlockSliceDefault
  | ProjectBlockSliceTwoImagesInARow
  | ProjectBlockSliceBigText
  | ProjectBlockSliceTwoColumnsText
  | ProjectBlockSliceGap
  | ProjectBlockSliceDivider;

/**
 * ProjectBlock Shared Slice
 *
 * - **API ID**: `project_block`
 * - **Description**: ProjectBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectBlockSlice = prismic.SharedSlice<'project_block', ProjectBlockSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<'default', Simplify<RichTextSliceDefaultPrimary>, never>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Item in *SecondScreenProject → Default → Primary → Tags*
 */
export interface SecondScreenProjectSliceDefaultPrimaryTagsItem {
  /**
   * Tag field in *SecondScreenProject → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_screen_project.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *SecondScreenProject → Default → Primary*
 */
export interface SecondScreenProjectSliceDefaultPrimary {
  /**
   * Background field in *SecondScreenProject → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_screen_project.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Project Name field in *SecondScreenProject → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_screen_project.default.primary.project_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_name: prismic.KeyTextField;

  /**
   * Project Place field in *SecondScreenProject → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_screen_project.default.primary.project_place
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_place: prismic.KeyTextField;

  /**
   * Thumbnail field in *SecondScreenProject → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_screen_project.default.primary.thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Tags field in *SecondScreenProject → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: second_screen_project.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<SecondScreenProjectSliceDefaultPrimaryTagsItem>>;
}

/**
 * Default variation for SecondScreenProject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondScreenProjectSliceDefault = prismic.SharedSliceVariation<'default', Simplify<SecondScreenProjectSliceDefaultPrimary>, never>;

/**
 * Slice variation for *SecondScreenProject*
 */
type SecondScreenProjectSliceVariation = SecondScreenProjectSliceDefault;

/**
 * SecondScreenProject Shared Slice
 *
 * - **API ID**: `second_screen_project`
 * - **Description**: SecondScreenProject
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondScreenProjectSlice = prismic.SharedSlice<'second_screen_project', SecondScreenProjectSliceVariation>;

/**
 * Item in *Services → Default → Primary → Services*
 */
export interface ServicesSliceDefaultPrimaryServicesItem {
  /**
   * Name field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Explanation field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].explanation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  explanation: prismic.RichTextField;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Services field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryServicesItem>>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<'default', Simplify<ServicesSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<'services', ServicesSliceVariation>;

/**
 * Item in *TripleC → Default → Primary → Terms*
 */
export interface TripleCSliceDefaultPrimaryTermsItem {
  /**
   * Label field in *TripleC → Default → Primary → Terms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: triple_c.default.primary.terms[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Image field in *TripleC → Default → Primary → Terms*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: triple_c.default.primary.terms[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TripleC → Default → Primary*
 */
export interface TripleCSliceDefaultPrimary {
  /**
   * Terms field in *TripleC → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: triple_c.default.primary.terms[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  terms: prismic.GroupField<Simplify<TripleCSliceDefaultPrimaryTermsItem>>;

  /**
   * Description field in *TripleC → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: triple_c.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TripleC Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripleCSliceDefault = prismic.SharedSliceVariation<'default', Simplify<TripleCSliceDefaultPrimary>, never>;

/**
 * Slice variation for *TripleC*
 */
type TripleCSliceVariation = TripleCSliceDefault;

/**
 * TripleC Shared Slice
 *
 * - **API ID**: `triple_c`
 * - **Description**: TripleC
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripleCSlice = prismic.SharedSlice<'triple_c', TripleCSliceVariation>;

/**
 * Item in *ProjectHeader → Default → Primary → Tags*
 */
export interface WorkHeaderSliceDefaultPrimaryTagsItem {
  /**
   * tag field in *ProjectHeader → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_header.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectHeader → Default → Primary*
 */
export interface WorkHeaderSliceDefaultPrimary {
  /**
   * Project Name field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_header.default.primary.project_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_name: prismic.KeyTextField;

  /**
   * Project Place field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_header.default.primary.project_place
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_place: prismic.KeyTextField;

  /**
   * Tags field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_header.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<WorkHeaderSliceDefaultPrimaryTagsItem>>;

  /**
   * Company Thumbnail field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_header.default.primary.company_thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_thumbnail: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkHeaderSliceDefault = prismic.SharedSliceVariation<'default', Simplify<WorkHeaderSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ProjectHeader*
 */
type WorkHeaderSliceVariation = WorkHeaderSliceDefault;

/**
 * ProjectHeader Shared Slice
 *
 * - **API ID**: `work_header`
 * - **Description**: WorkHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkHeaderSlice = prismic.SharedSlice<'work_header', WorkHeaderSliceVariation>;

/**
 * Item in *WorksScreen → Default → Primary → Works*
 */
export interface WorksScreenSliceDefaultPrimaryWorksItem {
  /**
   * Show Above the Table field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: works_screen.default.primary.works[].show_above_the_table
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_above_the_table: prismic.BooleanField;

  /**
   * Size field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<'small' | 'big'>;

  /**
   * Name field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Location field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Big Image field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].big_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  big_image: prismic.ImageField<never>;

  /**
   * Tag field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Thumbnail field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Work Reference ID field in *WorksScreen → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[].work_reference_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_reference_id: prismic.KeyTextField;
}

/**
 * Primary content in *WorksScreen → Default → Primary*
 */
export interface WorksScreenSliceDefaultPrimary {
  /**
   * Works field in *WorksScreen → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: works_screen.default.primary.works[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  works: prismic.GroupField<Simplify<WorksScreenSliceDefaultPrimaryWorksItem>>;
}

/**
 * Default variation for WorksScreen Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksScreenSliceDefault = prismic.SharedSliceVariation<'default', Simplify<WorksScreenSliceDefaultPrimary>, never>;

/**
 * Slice variation for *WorksScreen*
 */
type WorksScreenSliceVariation = WorksScreenSliceDefault;

/**
 * WorksScreen Shared Slice
 *
 * - **API ID**: `works_screen`
 * - **Description**: WorksScreen
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksScreenSlice = prismic.SharedSlice<'works_screen', WorksScreenSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      Work1Document,
      Work1DocumentData,
      Work1DocumentDataSlicesSlice,
      AllDocumentTypes,
      AbountUsSlice,
      AbountUsSliceDefaultPrimaryNumbersItem,
      AbountUsSliceDefaultPrimary,
      AbountUsSliceVariation,
      AbountUsSliceDefault,
      AwardsSlice,
      AwardsSliceDefaultPrimaryAwardsItem,
      AwardsSliceDefaultPrimary,
      AwardsSliceVariation,
      AwardsSliceDefault,
      ClientsSlice,
      ClientsSliceDefaultPrimaryClientsItem,
      ClientsSliceDefaultPrimary,
      ClientsSliceVariation,
      ClientsSliceDefault,
      IntroSlice,
      IntroSliceDefaultPrimaryIntroWorksItem,
      IntroSliceDefaultPrimary,
      IntroSliceVariation,
      IntroSliceDefault,
      ProjectBlockSlice,
      ProjectBlockSliceDefaultPrimary,
      ProjectBlockSliceTwoImagesInARowPrimary,
      ProjectBlockSliceBigTextPrimary,
      ProjectBlockSliceTwoColumnsTextPrimary,
      ProjectBlockSliceGapPrimary,
      ProjectBlockSliceDividerPrimary,
      ProjectBlockSliceVariation,
      ProjectBlockSliceDefault,
      ProjectBlockSliceTwoImagesInARow,
      ProjectBlockSliceBigText,
      ProjectBlockSliceTwoColumnsText,
      ProjectBlockSliceGap,
      ProjectBlockSliceDivider,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SecondScreenProjectSlice,
      SecondScreenProjectSliceDefaultPrimaryTagsItem,
      SecondScreenProjectSliceDefaultPrimary,
      SecondScreenProjectSliceVariation,
      SecondScreenProjectSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryServicesItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      TripleCSlice,
      TripleCSliceDefaultPrimaryTermsItem,
      TripleCSliceDefaultPrimary,
      TripleCSliceVariation,
      TripleCSliceDefault,
      WorkHeaderSlice,
      WorkHeaderSliceDefaultPrimaryTagsItem,
      WorkHeaderSliceDefaultPrimary,
      WorkHeaderSliceVariation,
      WorkHeaderSliceDefault,
      WorksScreenSlice,
      WorksScreenSliceDefaultPrimaryWorksItem,
      WorksScreenSliceDefaultPrimary,
      WorksScreenSliceVariation,
      WorksScreenSliceDefault,
    };
  }
}
